---
- name: Create directory structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ graphite_bin_dir }}"
    - "{{ graphite_conf_dir }}"
    - "{{ graphite_systemd_dir }}"

#TODO - find python version store in host_vars
- name: Setup graphite with pip
  pip:
    name: "{{ item }}"
    extra_args: > 
      --install-option='--prefix={{ graphite_dir }}'
      --install-option='--install-lib={{ graphite_virtualenv }}/lib/python2.7/site-packages'
      --no-binary=:all:
    virtualenv: "{{ graphite_virtualenv }}"
  with_items: "{{ graphite_carbon_pip_required }}"
  notify: restart carbon-cache

- name: Delete examples
  block:
    - find:
        paths: "{{ graphite_conf_dir }}"
        patterns: "*.example"
      register: files_to_delete

    - file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"

    - file:
        path: "{{ graphite_dir}}/examples"
        state: absent

- name: Install carbon configuration
  template:
    src: carbon/carbon.conf.j2
    dest: "{{ graphite_conf_dir }}/carbon.conf"
  notify: restart carbon-cache

- name: Install storage schemas
  template:
    src: carbon/storage-schemas.conf.j2
    dest: "{{ graphite_conf_dir }}/storage-schemas.conf"
  notify: restart carbon-cache

- name: Install carbon-cache systemd service
  template:
    src: carbon/carbon-cache.service.j2
    dest: "{{ graphite_systemd_dir }}/carbon-cache.service"
    owner: "{{ graphite_user }}"
    group: "{{ graphite_group }}"
  notify: restart carbon-cache

- name: Install carbon-cache environment file
  template:
    src: carbon/carbon-cache.env
    dest: "{{ graphite_systemd_dir }}/carbon-cache.env"
    owner: "{{ graphite_user }}"
    group: "{{ graphite_group }}"
  notify: restart carbon-cache

- name: Create symlink
  with_items:
    - { src: "{{ graphite_systemd_dir }}/carbon-cache.service", dest: "{{ graphite_os_systemd_dir }}/carbon-cache.service"}
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  notify:
    - enable carbon-cache
