---
- name: restart carbon-cache
  systemd:
    name: carbon-cache
    daemon_reload: yes
    state: restarted

- name: restart graphite-web
  systemd:
    name: graphite-web
    daemon_reload: yes
    state: restarted
